Create support from and to XML Document
polimorphic/xml-marshal pull request #1
Opened 2023-03-21 22:16 UTC by neil-menghani

2023-03-21 22:19 UTC, tysonzero requested changes

2023-03-21 22:19 UTC, tysonzero commented on src/Text/XML/Marshal.hs
> +import Text.XML
.

2023-03-21 22:33 UTC, neil-menghani commented on src/Text/XML/Marshal.hs
> +import Text.XML
Oops

2023-03-21 23:55 UTC, tysonzero requested changes
Fix up title and bump version to `0.1.0.0` as this is a breaking change

2023-03-22 00:06 UTC, tysonzero approved these changes

2023-03-22 00:08 UTC, merged